---
title: "又开学了"
date: '2010-09-02'
categories:
---

由于我经常发现自己所想的是错的，所以我已很少能断定什么，不过我确信一点，就是，我是爱这个世界的。

不过，我这人不信教，所以这一想法跟宗教情怀无关，由于紧接着要表达我的感恩，所以这一点要特别强调。

我很感激我遇到的人，有些人直接感动过我的，有些是我看着他们的生活的而被感动的（即自己的YY）。

有些人改变了我原有的想法（有些是极为难受的），甚至一些无意识的事件瞬间扭转了我对自己处境的评价。

当然，如果我遇到的都是当时就令我赏心悦目的人，那会让不信神的我都怀疑我是不是受到神的眷顾。

所以，事实，我也遇到了一些让我狼狈不堪的人，不甚潇洒的人。

不过呢，在我写篇博客的这个时候（也就是心情还比较好的时候），我依然是感谢他们的，因为他们让我了解到我自己可以丑恶到什么程度。

前几天看到一段话，蛮有感觉的，说的是“说话的时候太不认真，沉默的时候太认真”。

我会常怀感激，但是这个事情很难口头表达。

有些是因为我天朝上国的传统，即不怎么表达。

有些是因为，纯属自己感动自己，所以跟别人讲起来可能是吓到别人。

有些是因为，感激的对象不需要感恩。这一点很重要，因为你不能因为自己要发泄满腔的情绪，而让别人“被”感恩。

有些感恩，纯属针对我生活的这个世界。这一点指的是那些让我狼狈不堪的人，即使我心情舒畅了，我也不会大度到跑去感激他们，而只会感激这个世界给我的体验。

其实，在表达感恩这种私人情感的事情上。我这人不是很喜欢文字，因为我不够精通，难以运用得当。

能直接走过去拍拍你的肩膀，胜过一堆东拼西凑的文字。

<br>

如果一个人对什么都不确定的话，那他就只能到捣糨糊，所以可以说哥是蹉跎至今。

所以我之前一直追求确定性，希望能解决我自己的困境。但是慢慢我发现似乎这样不对，也许有其他的方式（更诚实的说，其实我无路可走想放

弃这条道路），特别是看到《确定性的丧失》这本书。

“权威”和“系统”信念的根源是相同的：对确定性的渴望。这是书里面说的。

更彻底的表明另外一条路径的，是我看到的这两句话：

> Everything we hear is an opinion not the fact. Everything we see is a perspective not the truth.

> All knowledge is human belief; more accurately human opinion.

但是，给我还原世界不确定性的本质，并不能让我感觉更踏实啊？这只能给我一贯的混沌无知找到借口，但是我该怎么做呢？

唉，要不怎么说我对这个世界常怀感激呢？不久前，我看到一个帖子，从她的经历里我找到了方法，那就是：对自己所做的事情必须有认同感。

> “另外，有件事情基本让我把 academia的门关上了。我老板让我写过一篇paper，是第一年时候做的一个东西，实话实说，我觉得没什么东西，事实证明，也是peer review批评比较多，我和老板说，要不算了，这玩意就算有发明也是点皮毛啦，没做什么实际的贡献。老板听我一说upset了，他指着他那满书架的 IEEE杂志，说你看看这一堆东西里面有几个是真正的revoluntion，多数的文章就是在灌水。这件事情对我影响很大，一个人不需要做什么惊天动地的大事，但是对自己做的事情必须有认同感，如果做学术的自己都觉得自己在灌水，理由是身边大多数人也是在灌水，那么我不明白我为什么要去做它。”



而我自己之前处于什么一种状态呢，简单讲，就是消极的淡定。

一切都不确定，一切都在变是吧？所以，对于漠不关心以及不屑的事情，那自然是极度的淡定；对于珍视的东西，则是目送这些惊鸿一现的美丽的离开，但是告诉自己要记住面对美丽时的感受。这个不难理解，打个比方，你很难苛求一个忐忑不安的锉男发出保有四海的豪情。

我曾经在签名上写“远山含黛，轻舟万里”给自己，想象着一个人一个躺在一条行船上，看着美不胜收的山水离自己而去的场景。

写到这里，我突然想起小钟，小淫虫小钟居然跟我感叹“生如浮萍”。如果你们能想象当世第一大淫贼突然口宣佛号化生为当世第一高僧的话，你们就能想象我当时的震撼。

（不好意思啊小钟！我并不是真的说你淫荡，但是由于我已经私底下叫惯了，而且此处不用些重口味的词，不足以表达强烈的情感，所以只好委屈你了。不过你放心，不认识你的人，不知道找小钟是谁；认识你的人，大家都知道小钟不淫荡。哈哈~）

当时，寝室昏暗的灯光下，我看到小钟平时滴溜乱转的小眼珠子是那么的严肃，明亮的镜片上面似乎生气一团雾气，当时我就恍惚了。

<br>

正如我开头说说，我很少能断定什么，因为对自己所做的事情没有认同感。现在，我发现不该断定什么，如果你对自己所做的事情有认同感的话。

但是，上面这句话可同时成为混沌无知和固执自我的借口，所以，那什么是重要的呢？

我觉得自己的感觉是最重要的，不管后来的想法怎么变来变去，当时的感受是真实的。我相信每个念起“当时明月”心有所动的人，都会同意我的观点。

所以，在开学前，我记录下自己的感觉。

祝自己在新的学期，好好学习，天天向上！^_^
