---
title: "毕业感言（被枪毙版）"
date: '2012-06-21'
categories:
---


各位老师、各位同学:

上午好！很高兴能有这个机会在这里发言。

我在社科院求学五年，五年里我最大的收获是得到了一份安定与自信的心态。所谓“安定与自信”的心态，简而言之，就是“淡定”。但是淡定这个东西既跟学术无关，也跟金钱无关，所以我要解释下为什么我这么看重这个东西。当然，了解我的人也可以把我下面的讲话当作我在社科院五年既没怎么搞学术，也没有出去兼职实习的借口。

我从六岁上学，至今在学校里呆了21年。在这21年中，我过得最淡定、最开心的日子是在中学阶段，那时候不用考虑自己与外界的关系，不用思考自己在这个世界中如何安放的问题。

但是上大学后，这种心态发生了改变，我开始变得不淡定，因为我开始畏惧我最终要走向的这个世界。我突然意识到，这个世界在我还没有准备好之前，就已经在那里貌似坚如磐石的运转多年了。

中学阶段未清楚的意识到外在世界的我所习惯的接受事物的方式是这样的：首先，会有大段的文本叙述，让你清楚你即将所处的大环境——也就说有一本教材详细介绍你该掌握的全部知识；其次，你会遇到各种局部环境和任务的设定——也就说有各种的题目和试卷去解答。但是，当外在世界进入我的生活，或者说我开始意识到外在于我的世界的时候，并没有一本《世界使用手册》来详细的介绍这个世界的各种特性。因此，我觉得我被困在未知和不确定当中。

糟糕的事情还不止如此。刚刚我说过，在我眼中，外在世界只是“貌似坚如磐石”的运行，但实际上我对这种坚如磐石的外表是心存怀疑的。因为我既不是造物主，也缺乏一本《世界使用手册》，我怎么知道这个外表坚如磐石的家伙存不存在错误？它其中的某些关联是不是本不该存在的扭曲？如果我沿着这些扭曲走下去，我会不会迎来我自己的悲惨世界呢？讲到这里，各位可能觉得我是不是脑袋有病。不过还好，佛家说过“因智而憎爱不等，随想而世界成差”，所以我觉得我的问题应该不大。

但是，有了这种恐惧之后，我就努力的去寻找出路。作为一个学生，自然的反应是觉得这些问题的答案能在书本中找到。所以我读完了本科读硕士，读完了硕士读博士，我希望在我走进这个世界之前，找到我的那本《世界使用手册》，然后就可以以一种“万物并作，吾以观复”的心情来欣赏这个世界的美景。顺便说下，我甚至把这本世界使用手册的名字都想好了，就叫《关于这个世界的一切以及其他》。

不过很可惜，我的这本《关于这个世界的一切以及其他》的小册子并没有产生，我从书中寻找答案的努力没有成功。因为每当我进入一个领域，对这个领域有着大致的了解之后，我就会发现，哦，这里提供不了我想要的答案。于是恐惧和对确定性的渴望驱使我从一个领域跳到另一个领域。在社科院的五年，我就是这样惶惶不可终日的过下来的，疲于奔命，却几无建树。在这里我非常感谢我的导师杨建文老师，他包容了我这种不学无术、无所事事的行为；我也很感谢研部的王晓丰老师，一直以来他对我“只看书不写文章”的行为都表示理解。

当一个人疲于奔命久了之后，就会累了，尤其当我自己跳来跳去兜了几个圈子之后，我常常发现我又回到了原点。于是我就想，是否我要获得《关于这个世界的一切以及其他》这本小册子的努力是徒劳的，我想在进入世界之前就获得关于世界的一切确定性是不可能的。老子所讲的“万物并作，吾以观复”，应该只是一种态度。我不了解万物造化的各种可能，但这并不妨碍我欣赏这个世界的风景；不是要将这个世界解剖清楚了，我才能乐在其中。有了这种心态，才能不怀疑、不恐惧，将自己有限的精力专注于某一领域，做出一些成果。

总结一下的话，我五年来得出的认识就是：世界就如同它所展现的样子，我该追求的不是确定性，而应该心存敬意但无所畏惧的生活。网上有句传言说“女生读博是因为情商低，男生读博是因为智商低”，但是我看我的女同学，个个玲珑剔透、淡然出尘，显然传言的前半句不适用；再看我的男同学，个个霸气外露、一骑绝尘，显然传言的后半句也不适用。可是我自己却花五年的时间总结出一句常识，可见即使我不是智商低的话，那也是极端的迟钝，不过由此可见，社科院给我提供了一个多么宽松、自由的学习环境。

无论如何，我认为我在社科院度过了很有意义的五年。传说青春有一种不幸是在你最美的时候，没有遇到你想见的人；而社科院在我最恐惧、最蹉跎的时候接纳了我，让我学习成长，让我能做对的自己，这是我的幸运，因此我很感激社科院！感谢院部和研部各位老师对我的指导！感谢善待我的同学！

我的讲话完了，谢谢大家！
